import pytest
import sys
import pandas as pd
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from scripts.run_e2e_pipeline import run_end_to_end
from storage.storage_manager import storage
from kafka.producers.stream_producer import StreamProducer
from kafka.consumers.raw_consumer import RawConsumer
from kafka.dlq.dead_letter import DLQHandler
from data.schemas.validator import SchemaValidator
from database.warehouse import WarehouseManager
from spark.etl.price_pipeline import PricePipeline
from dashboard.db_connector import DashboardDB

from storage.minio_backend import MinIOBackend
from config.settings import settings

def test_full_e2e_pipeline():
    # P0-1: Prove StorageManager.backend == MinIOBackend
    assert storage.backend == MinIOBackend
    assert storage.backend.bucket == settings.storage.data_lake_bucket

    success = run_end_to_end()
    assert success is True
    
    # P0-2: Verify MinIO Bronze raw batches exist
    bronze_topics = storage.list_bronze_topics()
    assert len(bronze_topics) > 0
    bronze_prods = storage.read_bronze_records("raw.products")
    assert len(bronze_prods) > 0

    # P0-3 & P1-1: Verify Silver Parquet generated by Spark Batch exists (products, reviews, prices)
    df_prods = storage.read_silver_parquet("products")
    df_revs = storage.read_silver_parquet("reviews")
    df_prices = storage.read_silver_parquet("prices")
    assert not df_prods.empty
    assert not df_revs.empty
    assert not df_prices.empty
    assert "product_id" in df_prods.columns
    assert "review_id" in df_revs.columns
    assert "price_id" in df_prices.columns

    # P0-4 & P1-1: Verify all 4 Gold Marts generated by SparkGoldBuilder exist
    df_p_gold = storage.read_gold_parquet("product_daily_stats")
    df_b_gold = storage.read_gold_parquet("brand_daily_stats")
    df_c_gold = storage.read_gold_parquet("category_daily_stats")
    df_pr_gold = storage.read_gold_parquet("price_daily_stats")
    assert not df_p_gold.empty
    assert not df_b_gold.empty
    assert not df_c_gold.empty
    assert not df_pr_gold.empty

    # P1-2: Verify Data Quality metrics and Anomaly events persisted
    df_dq = storage.read_gold_parquet("data_quality_metrics")
    assert not df_dq.empty
    df_anoms = storage.read_gold_parquet("anomaly_events")
    assert not df_anoms.empty

    # P0-5 & P1-4: Verify Warehouse and Dashboard connection
    db = DashboardDB()
    stats = db.get_product_daily_stats()
    assert not stats.empty
    kpis = db.get_kpi_summary()
    assert isinstance(kpis, dict)
    assert kpis["total_products"] > 0
    assert not db.get_price_daily_stats().empty
    assert not db.get_anomaly_events().empty
    assert not db.get_data_quality_metrics().empty

def test_kafka_producer_envelope_structure():
    """Verify that messages produced are wrapped in canonical envelope metadata."""
    producer = StreamProducer(enable_offline_buffer=True)
    sample_records = [
        {"review_id": "rv_test_001", "product_id": "p_01", "rating": 5.0, "review_text": "Superb"}
    ]
    sent, rate = producer.produce_batch(
        topic="raw.reviews",
        records=sample_records,
        rate=100.0,
        event_type="NEW_REVIEW",
        source="test_runner"
    )
    assert sent == 1
    assert len(producer.virtual_queue) >= 1
    
    msg = producer.virtual_queue[-1]["value"]
    assert "event_id" in msg
    assert msg["event_type"] == "NEW_REVIEW"
    assert msg["source"] == "test_runner"
    assert "ingested_at" in msg
    assert "payload" in msg
    assert msg["payload"]["review_id"] == "rv_test_001"

def test_kafka_producer_fail_loudly_when_offline():
    """Verify that when offline buffer is disabled and broker is unreachable, producer raises error."""
    # Using an invalid host should cause fail-loud behavior
    with pytest.raises(Exception):
        producer = StreamProducer(
            bootstrap_servers="127.0.0.1:59999",
            enable_offline_buffer=False
        )

def test_raw_consumer_bronze_partitioning():
    """Verify consumer creates partitioned directory structure in Bronze storage."""
    consumer = RawConsumer()
    test_batch = [
        {"product_id": "prod_x", "product_name": "Test Item", "timestamp": "2026-10-02T10:00:00Z"}
    ]
    out_file = consumer.save_raw_batch("raw.products", test_batch)
    assert out_file.exists()
    assert "year=2026" in str(out_file)
    assert "raw.products" in str(out_file)
    assert out_file.suffix == ".json"

def test_schema_validator_and_quarantine():
    """Verify SchemaValidator detects valid vs malformed records."""
    valid_record = {
        "price_id": "pr_001",
        "product_id": "prod_01",
        "price": 150000.0,
        "currency": "VND",
        "timestamp": "2026-10-02T10:00:00Z"
    }
    is_valid, errs = SchemaValidator.validate_record(valid_record, "price")
    assert is_valid is True
    assert len(errs) == 0

    invalid_record = {
        "price_id": "pr_002",
        # missing product_id
        "price": -50.0,  # invalid negative price
        "currency": "VND"
    }
    is_valid, errs = SchemaValidator.validate_record(invalid_record, "price")
    assert is_valid is False
    assert len(errs) > 0

    valid_list, invalid_list = SchemaValidator.validate_batch([valid_record, invalid_record], "price")
    assert len(valid_list) == 1
    assert len(invalid_list) == 1

def test_dead_letter_queue_handling():
    """Verify DLQ handler structures failed payloads properly."""
    dlq = DLQHandler()
    res = dlq.send_to_dlq(
        error_type="SCHEMA_VALIDATION_ERROR",
        source_topic="raw.reviews",
        partition=0,
        offset=42,
        payload={"corrupt": "data"},
        errors=["missing review_text"]
    )
    assert res is not None
    assert res["error_type"] == "SCHEMA_VALIDATION_ERROR"
    assert res["source_topic"] == "raw.reviews"
    assert "timestamp" in res

def test_warehouse_manager_upsert_idempotency():
    """Verify warehouse upsert operations are idempotent and do not duplicate primary keys."""
    wm = WarehouseManager(use_postgres=False)
    wm.initialize_schema()
    
    test_df = pd.DataFrame([
        {
            "date": "2026-10-01",
            "product_id": "prod_upsert_test",
            "review_count": 10,
            "avg_rating": 4.5,
            "min_price": 100000.0,
            "max_price": 100000.0,
            "avg_price": 100000.0,
            "rating_std": 0.2,
            "positive_ratio": 0.9,
            "negative_ratio": 0.1
        }
    ])
    
    # First insert
    affected1 = wm.upsert_dataframe("product_daily_stats", test_df, conflict_keys=["date", "product_id"])
    assert affected1 == 1
    
    # Second insert with updated avg_rating
    test_df_updated = test_df.copy()
    test_df_updated["avg_rating"] = 4.8
    affected2 = wm.upsert_dataframe("product_daily_stats", test_df_updated, conflict_keys=["date", "product_id"])
    assert affected2 == 1
    
    # Query to verify single row with updated rating
    res = wm.query("SELECT * FROM product_daily_stats WHERE product_id = 'prod_upsert_test'")
    assert len(res) == 1
    assert float(res["avg_rating"].iloc[0]) == 4.8

def test_price_pipeline_execution():
    """Verify PricePipeline cleans, validates, and standardizes price records."""
    raw_prices = [
        {"price_id": "pr_1", "product_id": "p_1", "price": "250000", "currency": "VND", "timestamp": "2026-10-02T10:00:00Z"},
        {"price_id": "pr_2", "product_id": "p_2", "price": -100, "currency": "VND", "timestamp": "2026-10-02T10:00:00Z"},
        {"price_id": "pr_3", "product_id": None, "price": 50000, "currency": "VND", "timestamp": "2026-10-02T10:00:00Z"}
    ]
    res = PricePipeline.run_pipeline(raw_prices, save_silver=False)
    assert res["prices_processed"] == 1  # Only pr_1 is valid
    assert res["prices_invalid"] == 2

def test_dashboard_db_connector():
    """Verify DashboardDB connector can query metrics."""
    db = DashboardDB()
    stats = db.get_product_daily_stats()
    assert isinstance(stats, pd.DataFrame)
    kpis = db.get_kpi_summary()
    assert isinstance(kpis, dict)
    assert "total_products" in kpis

def test_spark_data_quality_evaluator():
    """P1-2: Verify SparkDataQualityEvaluator metrics calculation and quarantine routing."""
    from spark.quality.spark_dq import SparkDataQualityEvaluator
    
    test_df = pd.DataFrame([
        {"id": "1", "val": 10},
        {"id": "2", "val": None},
        {"id": "1", "val": 10}  # duplicate
    ])
    metrics = SparkDataQualityEvaluator.evaluate(test_df, "test_dataset", primary_key="id")
    assert metrics["total_count"] == 3
    assert metrics["null_count"] == 1
    assert metrics["duplicate_count"] == 1
    assert metrics["dq_score"] < 100.0

    report = SparkDataQualityEvaluator.generate_report(metrics, batch_id="batch_test_01")
    assert report["batch_id"] == "batch_test_01"
    assert report["dataset_name"] == "test_dataset"

    quarantine_path = SparkDataQualityEvaluator.save_quarantine("test_dataset", test_df.iloc[[1]])
    assert quarantine_path is not None
    assert "quarantine/test_dataset" in quarantine_path

def test_prometheus_metrics_exporter():
    """P2-2: Verify Prometheus metrics exporter produces standard exposition telemetry."""
    from monitoring.metrics_exporter import SentinelMetricsExporter

    data = SentinelMetricsExporter.collect_all_metrics()
    assert "datalake" in data
    assert "warehouse" in data
    assert "bronze_bytes" in data["datalake"]

    prom_text = SentinelMetricsExporter.generate_prometheus_metrics()
    assert "sentinel_datalake_size_bytes" in prom_text
    assert "sentinel_data_quality_score" in prom_text
    assert "sentinel_warehouse_records" in prom_text

def test_airflow_dag_standalone_execution():
    """P2-1: Verify Airflow DAG executes sequentially without throwing errors."""
    from orchestration.dags.sentinel_daily_pipeline import run_dag_standalone, dag
    assert dag.dag_id == "sentinel_daily_pipeline"
    # Execute full standalone run
    run_dag_standalone()

def test_lakehouse_table_time_travel_and_upsert():
    """P2-3: Verify Lakehouse ACID transaction logs, Time Travel, and Upsert capabilities."""
    from storage.lakehouse import LakehouseTable

    table = LakehouseTable("test_lakehouse_entity", layer="silver")
    
    # Version 0: initial write
    df_v0 = pd.DataFrame([
        {"id": "rec_1", "status": "PENDING", "price": 100.0},
        {"id": "rec_2", "status": "PENDING", "price": 200.0}
    ])
    v0 = table.write(df_v0, mode="overwrite")
    assert v0 >= 0
    read_v0 = table.read(version=v0)
    assert len(read_v0) == 2

    # Version 1: Upsert updating rec_1 and adding rec_3
    df_upsert = pd.DataFrame([
        {"id": "rec_1", "status": "COMPLETED", "price": 150.0},
        {"id": "rec_3", "status": "PENDING", "price": 300.0}
    ])
    v1 = table.upsert(df_upsert, merge_keys=["id"])
    assert v1 > v0

    # Query latest (v1)
    read_latest = table.read()
    assert len(read_latest) == 3
    rec1_row = read_latest[read_latest["id"] == "rec_1"].iloc[0]
    assert rec1_row["status"] == "COMPLETED"
    assert rec1_row["price"] == 150.0

    # Time Travel query back to v0
    time_travel_v0 = table.read(version=v0)
    assert len(time_travel_v0) == 2
    rec1_v0 = time_travel_v0[time_travel_v0["id"] == "rec_1"].iloc[0]
    assert rec1_v0["status"] == "PENDING"
    assert rec1_v0["price"] == 100.0

    # History audit check
    history = table.get_history()
    assert len(history) >= 2
    assert any(h.get("operation") == "MERGE_UPSERT" for h in history)
